### ISSUE TITLE
Model Avatar in AutoDesk Maya

### ISSUE THREAD

**Issue by MarjanaKarzek** [MarjanaKarzek/ChiBa#1]
- [x] model body and head
- [x] add head to body
- [x] test import to Unity

**Comment by ToraScarlet** [comment]
![seite](https://user-images.githubusercontent.com/13218115/27131037-4533a986-5109-11e7-913e-2eb553764836.PNG)
![vorne](https://user-images.githubusercontent.com/13218115/27131039-465edf9c-5109-11e7-8744-c107a8a40a58.PNG)
