### ISSUE TITLE
Refactor Avatar View

### ISSUE THREAD

**Issue by MarjanaKarzek** [MarjanaKarzek/ChiBa#44]
- [x] Delete axis and caption
- [x] Set up Texture for Avatar
- [x] Choose right object loader (color, texture, lightning)
- [x] Delete redundant code

**Comment by natgra** [comment]
- [x] Delete axis and caption
- [ ] Set up Texture for Avatar
- [x] Choose right object loader (color, texture, lightning)
- [x] Delete redundant code
